import Mathlib
import GrandeFinale

/-!
# Exact syndrome-line incidence

This module formalizes the linear-algebraic content of
`prop:syndrome-line-normal-form` and `thm:syndrome-secant-exact` in
`experimental/asymptotic_rs_mca_frontiers.tex`.

For a linear syndrome map `H`, a word is explained off an error set `E` exactly
when its syndrome lies in the image of the words supported on `E`.  Consequently
support-wise MCA badness is exactly transverse incidence of an affine syndrome
line with that image.  The outer slope `Finset` deduplicates parameters that are
witnessed by more than one error set.

The results are stated for the kernel code of an arbitrary linear map.  The
Reed--Solomon specialization supplies the generalized Vandermonde parity-check
map and identifies the supported-error images with rational-normal-curve secant
spans.
-/

open scoped Classical

noncomputable section

namespace GrandeFinale.SyndromeLine

variable {D F W : Type*} [Field F] [AddCommGroup W] [Module F W]

/-- Words whose support is contained in `E`. -/
def supportedOn (E : Set D) : Submodule F (D → F) where
  carrier := {e | ∀ x, x ∉ E → e x = 0}
  zero_mem' := by simp
  add_mem' := by
    intro e f he hf x hx
    simp [he x hx, hf x hx]
  smul_mem' := by
    intro a e he x hx
    simp [he x hx]

/-- The syndrome subspace generated by errors supported on `E`. -/
def syndromeSpan (H : (D → F) →ₗ[F] W) (E : Set D) : Submodule F W :=
  (supportedOn E).map H

/-- A word is explained away from `E` by a codeword in `ker H`. -/
def ExplainedOff (H : (D → F) →ₗ[F] W) (E : Set D) (u : D → F) : Prop :=
  ∃ c, c ∈ H.ker ∧ ∀ x, x ∉ E → c x = u x

/-- Explanation off `E` is equivalent to membership in the supported-error
syndrome span.  This is the first assertion of
`prop:syndrome-line-normal-form`. -/
theorem explainedOff_iff_syndrome_mem (H : (D → F) →ₗ[F] W)
    (E : Set D) (u : D → F) :
    ExplainedOff H E u ↔ H u ∈ syndromeSpan H E := by
  constructor
  · rintro ⟨c, hc, hagree⟩
    refine ⟨u - c, ?_, ?_⟩
    · intro x hx
      change u x - c x = 0
      rw [hagree x hx, sub_self]
    · have hcz : H c = 0 := by simpa using hc
      simp [hcz]
  · rintro ⟨e, he, hHe⟩
    refine ⟨u - e, ?_, ?_⟩
    · change H (u - e) = 0
      rw [map_sub, hHe, sub_self]
    · intro x hx
      have he0 : e x = 0 := he x hx
      change u x - e x = u x
      rw [he0, sub_zero]

/-- The affine syndrome line generated by `u0,u1`. -/
def syndromeLine (H : (D → F) →ₗ[F] W) (u0 u1 : D → F) (γ : F) : W :=
  H u0 + γ • H u1

/-- Transverse badness for a fixed error set. -/
def TransverseBadOn (H : (D → F) →ₗ[F] W) (E : Set D)
    (u0 u1 : D → F) (γ : F) : Prop :=
  ExplainedOff H E (u0 + γ • u1) ∧
    ¬ (ExplainedOff H E u0 ∧ ExplainedOff H E u1)

/-- Fixed-error-set MCA badness is exactly transverse syndrome-line incidence.
This is equation `(3.2)` of `prop:syndrome-line-normal-form`. -/
theorem transverseBadOn_iff_syndromeLine (H : (D → F) →ₗ[F] W)
    (E : Set D) (u0 u1 : D → F) (γ : F) :
    TransverseBadOn H E u0 u1 γ ↔
      syndromeLine H u0 u1 γ ∈ syndromeSpan H E ∧
        ¬ (H u0 ∈ syndromeSpan H E ∧ H u1 ∈ syndromeSpan H E) := by
  simp only [TransverseBadOn, explainedOff_iff_syndrome_mem,
    syndromeLine, LinearMap.map_add, LinearMap.map_smul]

/-- A transverse affine line meets a submodule at at most one finite slope. -/
theorem syndromeLine_mem_unique (V : Submodule F W) (a b : W)
    (htransverse : ¬ (a ∈ V ∧ b ∈ V)) {γ1 γ2 : F}
    (h1 : a + γ1 • b ∈ V) (h2 : a + γ2 • b ∈ V) :
    γ1 = γ2 := by
  by_contra hne
  have hscalar : γ1 - γ2 ≠ 0 := sub_ne_zero.mpr hne
  have hscaled : (γ1 - γ2) • b ∈ V := by
    have hsub := V.sub_mem h1 h2
    simpa [sub_smul] using hsub
  have hb : b ∈ V := by
    have hinv := V.smul_mem (γ1 - γ2)⁻¹ hscaled
    simpa [smul_smul, hscalar] using hinv
  have ha : a ∈ V := by
    have hremove := V.sub_mem h1 (V.smul_mem γ1 hb)
    simpa using hremove
  exact htransverse ⟨ha, hb⟩

/-- Two bad slopes witnessed by the same error set are equal. -/
theorem transverseBadOn_unique (H : (D → F) →ₗ[F] W) (E : Set D)
    (u0 u1 : D → F) {γ1 γ2 : F}
    (h1 : TransverseBadOn H E u0 u1 γ1)
    (h2 : TransverseBadOn H E u0 u1 γ2) :
    γ1 = γ2 := by
  have h1' := (transverseBadOn_iff_syndromeLine H E u0 u1 γ1).mp h1
  have h2' := (transverseBadOn_iff_syndromeLine H E u0 u1 γ2).mp h2
  exact syndromeLine_mem_unique (syndromeSpan H E) (H u0) (H u1)
    h1'.2 h1'.1 h2'.1

section FiniteSlopes

variable [Fintype F] [DecidableEq F]

/-- The deduplicated bad-slope set for one fixed error set. -/
def badSlopesOnErrorSet (H : (D → F) →ₗ[F] W) (E : Set D)
    (u0 u1 : D → F) : Finset F :=
  Finset.univ.filter (TransverseBadOn H E u0 u1)

omit [DecidableEq F] in
/-- One fixed noncommon error support carries at most one finite slope. -/
theorem badSlopesOnErrorSet_card_le_one (H : (D → F) →ₗ[F] W)
    (E : Set D) (u0 u1 : D → F) :
    (badSlopesOnErrorSet H E u0 u1).card ≤ 1 := by
  rw [Finset.card_le_one_iff]
  intro γ1 γ2 hγ1 hγ2
  exact transverseBadOn_unique H E u0 u1
    (Finset.mem_filter.mp hγ1).2 (Finset.mem_filter.mp hγ2).2

section ErrorFamilies

variable [DecidableEq D]

/-- Bad slopes witnessed by at least one member of a finite error-set family.
The outer filter deduplicates slopes with multiple witnesses. -/
def badSlopeSetOnErrorFamily (H : (D → F) →ₗ[F] W)
    (errors : Finset (Finset D)) (u0 u1 : D → F) : Finset F :=
  Finset.univ.filter fun γ =>
    ∃ E ∈ errors, TransverseBadOn H (E : Set D) u0 u1 γ

/-- The corresponding transverse syndrome-line/secant incidence set. -/
def syndromeSecantSetOnErrorFamily (H : (D → F) →ₗ[F] W)
    (errors : Finset (Finset D)) (y0 y1 : W) : Finset F :=
  Finset.univ.filter fun γ =>
    ∃ E ∈ errors,
      y0 + γ • y1 ∈ syndromeSpan H (E : Set D) ∧
        ¬ (y0 ∈ syndromeSpan H (E : Set D) ∧
          y1 ∈ syndromeSpan H (E : Set D))

omit [DecidableEq F] [DecidableEq D] in
/-- Exact finite syndrome--secant compiler for a supplied error-set family. -/
theorem badSlopeSetOnErrorFamily_eq_syndromeSecantSet
    (H : (D → F) →ₗ[F] W) (errors : Finset (Finset D))
    (u0 u1 : D → F) :
    badSlopeSetOnErrorFamily H errors u0 u1 =
      syndromeSecantSetOnErrorFamily H errors (H u0) (H u1) := by
  ext γ
  simp only [badSlopeSetOnErrorFamily, syndromeSecantSetOnErrorFamily,
    Finset.mem_filter, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨E, hE, hbad⟩
    exact ⟨E, hE, (transverseBadOn_iff_syndromeLine H (E : Set D) u0 u1 γ).mp hbad⟩
  · rintro ⟨E, hE, hsecant⟩
    exact ⟨E, hE, (transverseBadOn_iff_syndromeLine H (E : Set D) u0 u1 γ).mpr hsecant⟩

omit [DecidableEq D] in
/-- The error-family bad-slope set is the union of its fixed-error-set cells. -/
theorem badSlopeSetOnErrorFamily_eq_biUnion
    (H : (D → F) →ₗ[F] W) (errors : Finset (Finset D))
    (u0 u1 : D → F) :
    badSlopeSetOnErrorFamily H errors u0 u1 =
      errors.biUnion fun E => badSlopesOnErrorSet H (E : Set D) u0 u1 := by
  ext γ
  simp [badSlopeSetOnErrorFamily, badSlopesOnErrorSet]

omit [DecidableEq D] in
/-- Finite incidence bound: the number of distinct bad slopes is at most the
number of available error sets. -/
theorem badSlopeSetOnErrorFamily_card_le
    (H : (D → F) →ₗ[F] W) (errors : Finset (Finset D))
    (u0 u1 : D → F) :
    (badSlopeSetOnErrorFamily H errors u0 u1).card ≤ errors.card := by
  rw [badSlopeSetOnErrorFamily_eq_biUnion]
  calc
    (errors.biUnion fun E => badSlopesOnErrorSet H (E : Set D) u0 u1).card
        ≤ ∑ E ∈ errors, (badSlopesOnErrorSet H (E : Set D) u0 u1).card :=
      Finset.card_biUnion_le
    _ ≤ ∑ _E ∈ errors, 1 := Finset.sum_le_sum fun E _hE =>
      badSlopesOnErrorSet_card_le_one H (E : Set D) u0 u1
    _ = errors.card := by simp

end ErrorFamilies
end FiniteSlopes

section FiniteDomain

variable [Fintype D] [DecidableEq D]

/-- The error span complementary to an agreement support `S`. -/
def syndromeSpanOffSupport (H : (D → F) →ₗ[F] W)
    (S : Finset D) : Submodule F W :=
  syndromeSpan H (Sᶜ : Set D)

omit [Fintype D] in
/-- Existing `GrandeFinale.Explained` for the kernel code is the same as
`ExplainedOff` on the complementary error set. -/
theorem explained_kernel_iff_explainedOff_compl
    (H : (D → F) →ₗ[F] W) (S : Finset D) (u : D → F) :
    GrandeFinale.Explained (H.ker : Set (D → F)) u S ↔
      ExplainedOff H (Sᶜ : Set D) u := by
  constructor
  · rintro ⟨c, hc, hagree⟩
    exact ⟨c, hc, fun x hx => hagree x (by simpa using hx)⟩
  · rintro ⟨c, hc, hagree⟩
    exact ⟨c, hc, fun x hx => hagree x (by simpa using hx)⟩

omit [Field F] [Fintype D] [DecidableEq D] in
/-- Simultaneous explanation is the conjunction of the two explanation
predicates. -/
theorem explainedPair_iff_explained_and (C : Set (D → F))
    (u0 u1 : D → F) (S : Finset D) :
    GrandeFinale.ExplainedPair C u0 u1 S ↔
      GrandeFinale.Explained C u0 S ∧ GrandeFinale.Explained C u1 S := by
  constructor
  · rintro ⟨c0, hc0, c1, hc1, h0, h1⟩
    exact ⟨⟨c0, hc0, h0⟩, ⟨c1, hc1, h1⟩⟩
  · rintro ⟨⟨c0, hc0, h0⟩, ⟨c1, hc1, h1⟩⟩
    exact ⟨c0, hc0, c1, hc1, h0, h1⟩

omit [Fintype D] in
/-- Existing pair explanation is the same as two complementary-error
explanations. -/
theorem explainedPair_kernel_iff_explainedOff_compl
    (H : (D → F) →ₗ[F] W) (S : Finset D) (u0 u1 : D → F) :
    GrandeFinale.ExplainedPair (H.ker : Set (D → F)) u0 u1 S ↔
      ExplainedOff H (Sᶜ : Set D) u0 ∧
        ExplainedOff H (Sᶜ : Set D) u1 := by
  rw [explainedPair_iff_explained_and]
  exact and_congr
    (explained_kernel_iff_explainedOff_compl H S u0)
    (explained_kernel_iff_explainedOff_compl H S u1)

/-- Support-wise badness on one specified agreement support. -/
def BadOnSupport (H : (D → F) →ₗ[F] W) (S : Finset D)
    (u0 u1 : D → F) (γ : F) : Prop :=
  GrandeFinale.Explained (H.ker : Set (D → F))
      (fun x => u0 x + γ * u1 x) S ∧
    ¬ GrandeFinale.ExplainedPair (H.ker : Set (D → F)) u0 u1 S

omit [Fintype D] in
/-- The support predicate is exactly transverse badness on the complementary
error set. -/
theorem badOnSupport_iff_transverseBadOn
    (H : (D → F) →ₗ[F] W) (S : Finset D)
    (u0 u1 : D → F) (γ : F) :
    BadOnSupport H S u0 u1 γ ↔
      TransverseBadOn H (Sᶜ : Set D) u0 u1 γ := by
  exact and_congr
    (explained_kernel_iff_explainedOff_compl H S (u0 + γ • u1))
    (not_congr (explainedPair_kernel_iff_explainedOff_compl H S u0 u1))

omit [Fintype D] in
/-- Syndrome-line normal form stated directly in the existing support-wise MCA
vocabulary. -/
theorem badOnSupport_iff_syndromeLine
    (H : (D → F) →ₗ[F] W) (S : Finset D)
    (u0 u1 : D → F) (γ : F) :
    BadOnSupport H S u0 u1 γ ↔
      syndromeLine H u0 u1 γ ∈ syndromeSpanOffSupport H S ∧
        ¬ (H u0 ∈ syndromeSpanOffSupport H S ∧
          H u1 ∈ syndromeSpanOffSupport H S) := by
  rw [badOnSupport_iff_transverseBadOn,
    transverseBadOn_iff_syndromeLine]
  rfl

section FiniteDomainAndSlopes

variable [Fintype F] [DecidableEq F]

/-- Bad slopes carried by one existing agreement support. -/
def badSlopesOnSupport (H : (D → F) →ₗ[F] W) (S : Finset D)
    (u0 u1 : D → F) : Finset F :=
  Finset.univ.filter (BadOnSupport H S u0 u1)

omit [Fintype D] [DecidableEq F] in
/-- One fixed noncommon agreement support carries at most one finite slope. -/
theorem badSlopesOnSupport_card_le_one
    (H : (D → F) →ₗ[F] W) (S : Finset D)
    (u0 u1 : D → F) :
    (badSlopesOnSupport H S u0 u1).card ≤ 1 := by
  have heq : badSlopesOnSupport H S u0 u1 =
      badSlopesOnErrorSet H (Sᶜ : Set D) u0 u1 := by
    ext γ
    simp only [badSlopesOnSupport, badSlopesOnErrorSet,
      Finset.mem_filter, Finset.mem_univ, true_and]
    exact badOnSupport_iff_transverseBadOn H S u0 u1 γ
  rw [heq]
  exact badSlopesOnErrorSet_card_le_one H (Sᶜ : Set D) u0 u1

/-- Bad slopes witnessed by a supplied finite agreement-support family. -/
def badSlopeSetOnSupportFamily (H : (D → F) →ₗ[F] W)
    (supports : Finset (Finset D)) (u0 u1 : D → F) : Finset F :=
  Finset.univ.filter fun γ =>
    ∃ S ∈ supports, BadOnSupport H S u0 u1 γ

/-- The exact syndrome--secant set indexed by agreement supports. -/
def syndromeSecantSetOnSupportFamily (H : (D → F) →ₗ[F] W)
    (supports : Finset (Finset D)) (y0 y1 : W) : Finset F :=
  Finset.univ.filter fun γ =>
    ∃ S ∈ supports,
      y0 + γ • y1 ∈ syndromeSpanOffSupport H S ∧
        ¬ (y0 ∈ syndromeSpanOffSupport H S ∧
          y1 ∈ syndromeSpanOffSupport H S)

omit [Fintype D] [DecidableEq F] in
/-- Exact support-family syndrome--secant compiler. -/
theorem badSlopeSetOnSupportFamily_eq_syndromeSecantSet
    (H : (D → F) →ₗ[F] W) (supports : Finset (Finset D))
    (u0 u1 : D → F) :
    badSlopeSetOnSupportFamily H supports u0 u1 =
      syndromeSecantSetOnSupportFamily H supports (H u0) (H u1) := by
  ext γ
  simp only [badSlopeSetOnSupportFamily, syndromeSecantSetOnSupportFamily,
    Finset.mem_filter, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨S, hS, hbad⟩
    exact ⟨S, hS, (badOnSupport_iff_syndromeLine H S u0 u1 γ).mp hbad⟩
  · rintro ⟨S, hS, hsecant⟩
    exact ⟨S, hS, (badOnSupport_iff_syndromeLine H S u0 u1 γ).mpr hsecant⟩

omit [Fintype D] [DecidableEq D] in
/-- The support-family bad-slope set is the union of its fixed-support cells. -/
theorem badSlopeSetOnSupportFamily_eq_biUnion
    (H : (D → F) →ₗ[F] W) (supports : Finset (Finset D))
    (u0 u1 : D → F) :
    badSlopeSetOnSupportFamily H supports u0 u1 =
      supports.biUnion fun S => badSlopesOnSupport H S u0 u1 := by
  ext γ
  simp [badSlopeSetOnSupportFamily, badSlopesOnSupport]

omit [Fintype D] in
/-- Exact support-atlas incidence bound for an arbitrary finite family. -/
theorem badSlopeSetOnSupportFamily_card_le
    (H : (D → F) →ₗ[F] W) (supports : Finset (Finset D))
    (u0 u1 : D → F) :
    (badSlopeSetOnSupportFamily H supports u0 u1).card ≤ supports.card := by
  rw [badSlopeSetOnSupportFamily_eq_biUnion]
  calc
    (supports.biUnion fun S => badSlopesOnSupport H S u0 u1).card
        ≤ ∑ S ∈ supports, (badSlopesOnSupport H S u0 u1).card :=
      Finset.card_biUnion_le
    _ ≤ ∑ _S ∈ supports, 1 := Finset.sum_le_sum fun S _hS =>
      badSlopesOnSupport_card_le_one H S u0 u1
    _ = supports.card := by simp

/-- All agreement supports at threshold `a`. -/
def supportsAtLeast (a : Nat) : Finset (Finset D) :=
  Finset.univ.filter fun S : Finset D => a ≤ S.card

/-- The existing MCA-bad slope set for the kernel code. -/
def mcaBadSlopes (H : (D → F) →ₗ[F] W) (u0 u1 : D → F)
    (a : Nat) : Finset F :=
  Finset.univ.filter fun γ =>
    GrandeFinale.MCABad (H.ker : Set (D → F)) u0 u1 a γ

omit [DecidableEq D] [DecidableEq F] in
/-- Existing MCA bad slopes are exactly the union over their witness supports. -/
theorem mcaBadSlopes_eq_badSlopeSetOnSupportFamily
    (H : (D → F) →ₗ[F] W) (u0 u1 : D → F) (a : Nat) :
    mcaBadSlopes H u0 u1 a =
      badSlopeSetOnSupportFamily H (supportsAtLeast a) u0 u1 := by
  ext γ
  simp [mcaBadSlopes, badSlopeSetOnSupportFamily, supportsAtLeast,
    GrandeFinale.MCABad, BadOnSupport]

/-- Error sets of size at most `t`. -/
def errorSetsAtMost (t : Nat) : Finset (Finset D) :=
  Finset.univ.filter fun E : Finset D => E.card ≤ t

/-- The deduplicated transverse syndrome--secant slopes for errors of size at
most `t`. -/
def transverseSecantSlopes (H : (D → F) →ₗ[F] W)
    (t : Nat) (y0 y1 : W) : Finset F :=
  syndromeSecantSetOnErrorFamily H (errorSetsAtMost t) y0 y1

omit [DecidableEq D] [DecidableEq F] in
/-- Membership form of the transverse syndrome--secant count `(3.3)`. -/
theorem mem_transverseSecantSlopes_iff
    (H : (D → F) →ₗ[F] W) (t : Nat) (y0 y1 : W) (γ : F) :
    γ ∈ transverseSecantSlopes H t y0 y1 ↔
      ∃ E : Finset D, E.card ≤ t ∧
        y0 + γ • y1 ∈ syndromeSpan H (E : Set D) ∧
          ¬ (y0 ∈ syndromeSpan H (E : Set D) ∧
            y1 ∈ syndromeSpan H (E : Set D)) := by
  simp [transverseSecantSlopes, syndromeSecantSetOnErrorFamily, errorSetsAtMost]

/-- Agreement size and complementary error size give the same threshold. -/
theorem agreement_card_iff_compl_card (S : Finset D) {a : Nat}
    (ha : a ≤ Fintype.card D) :
    a ≤ S.card ↔ (Sᶜ).card ≤ Fintype.card D - a := by
  rw [Finset.card_compl]
  have hSn : S.card ≤ Fintype.card D := by
    simpa using Finset.card_le_card (Finset.subset_univ S)
  omega

omit [DecidableEq F] in
/-- Exact slope-set version of `thm:syndrome-secant-exact` for an arbitrary
surjective or nonsurjective syndrome map.  Surjectivity is needed only when the
maximum is moved from received pairs to all syndrome pairs. -/
theorem mcaBadSlopes_eq_transverseSecantSlopes
    (H : (D → F) →ₗ[F] W) (u0 u1 : D → F) {a : Nat}
    (ha : a ≤ Fintype.card D) :
    mcaBadSlopes H u0 u1 a =
      transverseSecantSlopes H (Fintype.card D - a) (H u0) (H u1) := by
  ext γ
  constructor
  · intro hγ
    have hbad := (Finset.mem_filter.mp hγ).2
    rcases hbad with ⟨S, hSa, hline, hpair⟩
    have hsupport : BadOnSupport H S u0 u1 γ := ⟨hline, hpair⟩
    have hsecant := (badOnSupport_iff_syndromeLine H S u0 u1 γ).mp hsupport
    apply (mem_transverseSecantSlopes_iff H _ _ _ γ).mpr
    refine ⟨Sᶜ, (agreement_card_iff_compl_card S ha).mp hSa, ?_⟩
    simpa [syndromeSpanOffSupport] using hsecant
  · intro hγ
    rcases (mem_transverseSecantSlopes_iff H _ _ _ γ).mp hγ with
      ⟨E, hEcard, hsecant⟩
    have hScard : a ≤ (Eᶜ).card := by
      apply (agreement_card_iff_compl_card (Eᶜ) ha).mpr
      simpa using hEcard
    have hsupport : BadOnSupport H Eᶜ u0 u1 γ := by
      apply (badOnSupport_iff_syndromeLine H Eᶜ u0 u1 γ).mpr
      simpa [syndromeSpanOffSupport] using hsecant
    apply Finset.mem_filter.mpr
    exact ⟨Finset.mem_univ γ, ⟨Eᶜ, hScard, hsupport.1, hsupport.2⟩⟩

/-- The exact transverse syndrome--secant numerator at error budget `t`. -/
def syndromeSecantNumerator [Fintype W] [DecidableEq W]
    (H : (D → F) →ₗ[F] W) (t : Nat) : Nat :=
  Finset.univ.sup fun p : W × W =>
    (transverseSecantSlopes H t p.1 p.2).card

omit [DecidableEq F] in
set_option maxHeartbeats 800000 in
/-- Exact numerator equality `(3.4)`: for a surjective syndrome map, maximizing
over received pairs is the same as maximizing over all syndrome pairs. -/
theorem B_MCA_eq_syndromeSecantNumerator
    [Fintype W] [DecidableEq W]
    (H : (D → F) →ₗ[F] W) (hH : Function.Surjective H)
    {a : Nat} (ha : a ≤ Fintype.card D) :
    GrandeFinale.B_MCA (H.ker : Set (D → F)) a =
      syndromeSecantNumerator H (Fintype.card D - a) := by
  change
    (Finset.univ.sup fun p : (D → F) × (D → F) =>
      (mcaBadSlopes H p.1 p.2 a).card) =
    Finset.univ.sup fun y : W × W =>
      (transverseSecantSlopes H (Fintype.card D - a) y.1 y.2).card
  apply le_antisymm
  · refine Finset.sup_le fun p _hp => ?_
    rw [mcaBadSlopes_eq_transverseSecantSlopes H p.1 p.2 ha]
    exact Finset.le_sup
      (f := fun y : W × W =>
        (transverseSecantSlopes H (Fintype.card D - a) y.1 y.2).card)
      (Finset.mem_univ (H p.1, H p.2))
  · refine Finset.sup_le fun y _hy => ?_
    obtain ⟨u0, hu0⟩ := hH y.1
    obtain ⟨u1, hu1⟩ := hH y.2
    rw [← hu0, ← hu1,
      ← mcaBadSlopes_eq_transverseSecantSlopes H u0 u1 ha]
    exact Finset.le_sup
      (f := fun p : (D → F) × (D → F) =>
        (mcaBadSlopes H p.1 p.2 a).card)
      (Finset.mem_univ (u0, u1))

end FiniteDomainAndSlopes
end FiniteDomain

#print axioms explainedOff_iff_syndrome_mem
#print axioms transverseBadOn_iff_syndromeLine
#print axioms badSlopeSetOnErrorFamily_eq_syndromeSecantSet
#print axioms badSlopeSetOnErrorFamily_card_le
#print axioms badOnSupport_iff_syndromeLine
#print axioms badSlopeSetOnSupportFamily_card_le
#print axioms mcaBadSlopes_eq_transverseSecantSlopes
#print axioms B_MCA_eq_syndromeSecantNumerator

end GrandeFinale.SyndromeLine
